basePath: /
consumes:
    - application/json
definitions:
    UserResponse:
        description: The user data is returned in the response
        properties:
            email:
                description: |-
                    email
                    in: body
                type: string
                x-go-name: Email
            role:
                description: |-
                    role
                    in: body
                type: string
                x-go-name: Role
            user_id:
                description: |-
                    user id
                    in: body
                type: string
                x-go-name: ID
            username:
                description: |-
                    username
                    in: body
                type: string
                x-go-name: Username
        type: object
        x-go-package: github.com/MousaZa/library-app-go/auth/server
info:
    description: Documentation for Auth API
    title: of Auth API
    version: 1.0.0
paths:
    /auth/create:
        post:
            operationId: createUser
            responses:
                "201":
                    $ref: '#/responses/noContent'
            tags:
                - auth
    /auth/delete/{id}:
        post:
            operationId: deleteUser
            responses:
                "201":
                    $ref: '#/responses/noContent'
            tags:
                - auth
    /auth/list/users:
        get:
            operationId: ListUsers
            responses:
                "200":
                    $ref: '#/responses/usersResponse'
            tags:
                - auth
    /auth/login:
        post:
            operationId: login
            parameters:
                - description: username
                  in: body
                  name: username
                  required: true
                  schema:
                    type: string
                  x-go-name: Username
                - description: password
                  in: body
                  name: password
                  required: true
                  schema:
                    type: string
                  x-go-name: Password
            responses:
                "200":
                    $ref: '#/responses/loginResponse'
            tags:
                - auth
    /auth/user:
        get:
            operationId: getUserData
            responses:
                "200":
                    $ref: '#/responses/userResponse'
            tags:
                - auth
produces:
    - application/json
responses:
    loginResponse:
        description: A token is returned in the response
    noContent:
        description: ""
    usersResponse:
        description: A list of user data is returned in the response
        headers:
            body:
                items:
                    $ref: '#/definitions/UserResponse'
                type: array
schemes:
    - http
swagger: "2.0"
