basePath: /
consumes:
    - application/json
definitions:
    createUserRequest:
        properties:
            email:
                description: email
                type: string
                x-go-name: Email
            password:
                description: password
                type: string
                x-go-name: Password
            username:
                description: username
                type: string
                x-go-name: Username
        type: object
        x-go-package: github.com/MousaZa/library-app-go/auth/server
    loginRequest:
        properties:
            password:
                description: password
                type: string
                x-go-name: Password
            username:
                description: username
                type: string
                x-go-name: Username
        type: object
        x-go-package: github.com/MousaZa/library-app-go/auth/server
    userResponse:
        properties:
            email:
                description: email
                type: string
                x-go-name: Email
            role:
                description: role
                type: string
                x-go-name: Role
            user_id:
                description: user id
                type: string
                x-go-name: ID
            username:
                description: username
                type: string
                x-go-name: Username
        type: object
        x-go-package: github.com/MousaZa/library-app-go/auth/server
info:
    description: Documentation for Auth API
    title: of Auth API
    version: 1.0.0
paths:
    /auth/create:
        post:
            operationId: createUser
            parameters:
                - description: The User data
                  in: body
                  name: Body
                  required: true
                  schema:
                    $ref: '#/definitions/createUserRequest'
            responses:
                "201":
                    $ref: '#/responses/noContent'
            tags:
                - auth
    /auth/delete/{id}:
        post:
            operationId: deleteUser
            parameters:
                - description: the id of the target user
                  format: int64
                  in: path
                  name: id
                  required: true
                  type: integer
                  x-go-name: ID
            responses:
                "201":
                    $ref: '#/responses/noContent'
            tags:
                - auth
    /auth/list/users:
        get:
            operationId: ListUsers
            responses:
                "200":
                    $ref: '#/responses/usersResponse'
            tags:
                - auth
    /auth/login:
        post:
            operationId: login
            parameters:
                - in: body
                  name: Body
                  schema:
                    $ref: '#/definitions/loginRequest'
            responses:
                "200":
                    $ref: '#/responses/loginResponse'
            tags:
                - auth
    /auth/user:
        get:
            operationId: getUserData
            responses:
                "200":
                    description: userResponse
                    schema:
                        $ref: '#/definitions/userResponse'
            tags:
                - auth
produces:
    - application/json
responses:
    loginResponse:
        description: A token is returned in the response
    noContent:
        description: ""
    usersResponse:
        description: A list of user data is returned in the response
        schema:
            type: array
            items:
                $ref: '#/definitions/userResponse'
schemes:
    - http
swagger: "2.0"