// Code generated by protoc-gen-go. DO NOT EDIT.
// source: borrows.proto

package borrows

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Borrow Model
type Borrow struct {
	Id                   int64                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	BookId               int64                  `protobuf:"varint,2,opt,name=BookId,proto3" json:"BookId,omitempty"`
	UserId               int64                  `protobuf:"varint,3,opt,name=UserId,proto3" json:"UserId,omitempty"`
	BorrowDate           *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=BorrowDate,proto3" json:"BorrowDate,omitempty"`
	ReturnDate           *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=ReturnDate,proto3" json:"ReturnDate,omitempty"`
	Status               string                 `protobuf:"bytes,6,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Borrow) Reset()         { *m = Borrow{} }
func (m *Borrow) String() string { return proto.CompactTextString(m) }
func (*Borrow) ProtoMessage()    {}
func (*Borrow) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a5779074719ee4c, []int{0}
}

func (m *Borrow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Borrow.Unmarshal(m, b)
}
func (m *Borrow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Borrow.Marshal(b, m, deterministic)
}
func (m *Borrow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Borrow.Merge(m, src)
}
func (m *Borrow) XXX_Size() int {
	return xxx_messageInfo_Borrow.Size(m)
}
func (m *Borrow) XXX_DiscardUnknown() {
	xxx_messageInfo_Borrow.DiscardUnknown(m)
}

var xxx_messageInfo_Borrow proto.InternalMessageInfo

func (m *Borrow) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Borrow) GetBookId() int64 {
	if m != nil {
		return m.BookId
	}
	return 0
}

func (m *Borrow) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Borrow) GetBorrowDate() *timestamppb.Timestamp {
	if m != nil {
		return m.BorrowDate
	}
	return nil
}

func (m *Borrow) GetReturnDate() *timestamppb.Timestamp {
	if m != nil {
		return m.ReturnDate
	}
	return nil
}

func (m *Borrow) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type MessageResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageResponse) Reset()         { *m = MessageResponse{} }
func (m *MessageResponse) String() string { return proto.CompactTextString(m) }
func (*MessageResponse) ProtoMessage()    {}
func (*MessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a5779074719ee4c, []int{1}
}

func (m *MessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageResponse.Unmarshal(m, b)
}
func (m *MessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageResponse.Marshal(b, m, deterministic)
}
func (m *MessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageResponse.Merge(m, src)
}
func (m *MessageResponse) XXX_Size() int {
	return xxx_messageInfo_MessageResponse.Size(m)
}
func (m *MessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MessageResponse proto.InternalMessageInfo

func (m *MessageResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// ADD
type AddBorrowRequest struct {
	BookId               int64    `protobuf:"varint,1,opt,name=BookId,proto3" json:"BookId,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddBorrowRequest) Reset()         { *m = AddBorrowRequest{} }
func (m *AddBorrowRequest) String() string { return proto.CompactTextString(m) }
func (*AddBorrowRequest) ProtoMessage()    {}
func (*AddBorrowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a5779074719ee4c, []int{2}
}

func (m *AddBorrowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddBorrowRequest.Unmarshal(m, b)
}
func (m *AddBorrowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddBorrowRequest.Marshal(b, m, deterministic)
}
func (m *AddBorrowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddBorrowRequest.Merge(m, src)
}
func (m *AddBorrowRequest) XXX_Size() int {
	return xxx_messageInfo_AddBorrowRequest.Size(m)
}
func (m *AddBorrowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddBorrowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddBorrowRequest proto.InternalMessageInfo

func (m *AddBorrowRequest) GetBookId() int64 {
	if m != nil {
		return m.BookId
	}
	return 0
}

func (m *AddBorrowRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

// UPDATE
type UpdateBorrowRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateBorrowRequest) Reset()         { *m = UpdateBorrowRequest{} }
func (m *UpdateBorrowRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateBorrowRequest) ProtoMessage()    {}
func (*UpdateBorrowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a5779074719ee4c, []int{3}
}

func (m *UpdateBorrowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateBorrowRequest.Unmarshal(m, b)
}
func (m *UpdateBorrowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateBorrowRequest.Marshal(b, m, deterministic)
}
func (m *UpdateBorrowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateBorrowRequest.Merge(m, src)
}
func (m *UpdateBorrowRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateBorrowRequest.Size(m)
}
func (m *UpdateBorrowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateBorrowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateBorrowRequest proto.InternalMessageInfo

func (m *UpdateBorrowRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateBorrowRequest) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type UpdateBorrowResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateBorrowResponse) Reset()         { *m = UpdateBorrowResponse{} }
func (m *UpdateBorrowResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateBorrowResponse) ProtoMessage()    {}
func (*UpdateBorrowResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a5779074719ee4c, []int{4}
}

func (m *UpdateBorrowResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateBorrowResponse.Unmarshal(m, b)
}
func (m *UpdateBorrowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateBorrowResponse.Marshal(b, m, deterministic)
}
func (m *UpdateBorrowResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateBorrowResponse.Merge(m, src)
}
func (m *UpdateBorrowResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateBorrowResponse.Size(m)
}
func (m *UpdateBorrowResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateBorrowResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateBorrowResponse proto.InternalMessageInfo

func (m *UpdateBorrowResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// DELETE
type DeleteBorrowRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteBorrowRequest) Reset()         { *m = DeleteBorrowRequest{} }
func (m *DeleteBorrowRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteBorrowRequest) ProtoMessage()    {}
func (*DeleteBorrowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a5779074719ee4c, []int{5}
}

func (m *DeleteBorrowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteBorrowRequest.Unmarshal(m, b)
}
func (m *DeleteBorrowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteBorrowRequest.Marshal(b, m, deterministic)
}
func (m *DeleteBorrowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteBorrowRequest.Merge(m, src)
}
func (m *DeleteBorrowRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteBorrowRequest.Size(m)
}
func (m *DeleteBorrowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteBorrowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteBorrowRequest proto.InternalMessageInfo

func (m *DeleteBorrowRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

// GET
type GetBookBorrowsRequest struct {
	BookId               int64    `protobuf:"varint,1,opt,name=BookId,proto3" json:"BookId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBookBorrowsRequest) Reset()         { *m = GetBookBorrowsRequest{} }
func (m *GetBookBorrowsRequest) String() string { return proto.CompactTextString(m) }
func (*GetBookBorrowsRequest) ProtoMessage()    {}
func (*GetBookBorrowsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a5779074719ee4c, []int{6}
}

func (m *GetBookBorrowsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBookBorrowsRequest.Unmarshal(m, b)
}
func (m *GetBookBorrowsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBookBorrowsRequest.Marshal(b, m, deterministic)
}
func (m *GetBookBorrowsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBookBorrowsRequest.Merge(m, src)
}
func (m *GetBookBorrowsRequest) XXX_Size() int {
	return xxx_messageInfo_GetBookBorrowsRequest.Size(m)
}
func (m *GetBookBorrowsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBookBorrowsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBookBorrowsRequest proto.InternalMessageInfo

func (m *GetBookBorrowsRequest) GetBookId() int64 {
	if m != nil {
		return m.BookId
	}
	return 0
}

type GetUserBorrowsRequest struct {
	UserId               int64    `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserBorrowsRequest) Reset()         { *m = GetUserBorrowsRequest{} }
func (m *GetUserBorrowsRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserBorrowsRequest) ProtoMessage()    {}
func (*GetUserBorrowsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a5779074719ee4c, []int{7}
}

func (m *GetUserBorrowsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserBorrowsRequest.Unmarshal(m, b)
}
func (m *GetUserBorrowsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserBorrowsRequest.Marshal(b, m, deterministic)
}
func (m *GetUserBorrowsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserBorrowsRequest.Merge(m, src)
}
func (m *GetUserBorrowsRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserBorrowsRequest.Size(m)
}
func (m *GetUserBorrowsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserBorrowsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserBorrowsRequest proto.InternalMessageInfo

func (m *GetUserBorrowsRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type GetUserOnGoingBorrowsRequest struct {
	UserId               int64    `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserOnGoingBorrowsRequest) Reset()         { *m = GetUserOnGoingBorrowsRequest{} }
func (m *GetUserOnGoingBorrowsRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserOnGoingBorrowsRequest) ProtoMessage()    {}
func (*GetUserOnGoingBorrowsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a5779074719ee4c, []int{8}
}

func (m *GetUserOnGoingBorrowsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserOnGoingBorrowsRequest.Unmarshal(m, b)
}
func (m *GetUserOnGoingBorrowsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserOnGoingBorrowsRequest.Marshal(b, m, deterministic)
}
func (m *GetUserOnGoingBorrowsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserOnGoingBorrowsRequest.Merge(m, src)
}
func (m *GetUserOnGoingBorrowsRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserOnGoingBorrowsRequest.Size(m)
}
func (m *GetUserOnGoingBorrowsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserOnGoingBorrowsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserOnGoingBorrowsRequest proto.InternalMessageInfo

func (m *GetUserOnGoingBorrowsRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type GetAllBorrowsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllBorrowsRequest) Reset()         { *m = GetAllBorrowsRequest{} }
func (m *GetAllBorrowsRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllBorrowsRequest) ProtoMessage()    {}
func (*GetAllBorrowsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a5779074719ee4c, []int{9}
}

func (m *GetAllBorrowsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllBorrowsRequest.Unmarshal(m, b)
}
func (m *GetAllBorrowsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllBorrowsRequest.Marshal(b, m, deterministic)
}
func (m *GetAllBorrowsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllBorrowsRequest.Merge(m, src)
}
func (m *GetAllBorrowsRequest) XXX_Size() int {
	return xxx_messageInfo_GetAllBorrowsRequest.Size(m)
}
func (m *GetAllBorrowsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllBorrowsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllBorrowsRequest proto.InternalMessageInfo

type GetBorrowsResponse struct {
	Borrows              []*Borrow `protobuf:"bytes,1,rep,name=borrows,proto3" json:"borrows,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetBorrowsResponse) Reset()         { *m = GetBorrowsResponse{} }
func (m *GetBorrowsResponse) String() string { return proto.CompactTextString(m) }
func (*GetBorrowsResponse) ProtoMessage()    {}
func (*GetBorrowsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a5779074719ee4c, []int{10}
}

func (m *GetBorrowsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBorrowsResponse.Unmarshal(m, b)
}
func (m *GetBorrowsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBorrowsResponse.Marshal(b, m, deterministic)
}
func (m *GetBorrowsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBorrowsResponse.Merge(m, src)
}
func (m *GetBorrowsResponse) XXX_Size() int {
	return xxx_messageInfo_GetBorrowsResponse.Size(m)
}
func (m *GetBorrowsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBorrowsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBorrowsResponse proto.InternalMessageInfo

func (m *GetBorrowsResponse) GetBorrows() []*Borrow {
	if m != nil {
		return m.Borrows
	}
	return nil
}

func init() {
	proto.RegisterType((*Borrow)(nil), "Borrow")
	proto.RegisterType((*MessageResponse)(nil), "MessageResponse")
	proto.RegisterType((*AddBorrowRequest)(nil), "AddBorrowRequest")
	proto.RegisterType((*UpdateBorrowRequest)(nil), "UpdateBorrowRequest")
	proto.RegisterType((*UpdateBorrowResponse)(nil), "UpdateBorrowResponse")
	proto.RegisterType((*DeleteBorrowRequest)(nil), "DeleteBorrowRequest")
	proto.RegisterType((*GetBookBorrowsRequest)(nil), "GetBookBorrowsRequest")
	proto.RegisterType((*GetUserBorrowsRequest)(nil), "GetUserBorrowsRequest")
	proto.RegisterType((*GetUserOnGoingBorrowsRequest)(nil), "GetUserOnGoingBorrowsRequest")
	proto.RegisterType((*GetAllBorrowsRequest)(nil), "GetAllBorrowsRequest")
	proto.RegisterType((*GetBorrowsResponse)(nil), "GetBorrowsResponse")
}

func init() {
	proto.RegisterFile("borrows.proto", fileDescriptor_0a5779074719ee4c)
}

var fileDescriptor_0a5779074719ee4c = []byte{
	// 435 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0xe1, 0x6a, 0xd4, 0x40,
	0x10, 0xc7, 0xd9, 0x9c, 0x5e, 0xb8, 0xa9, 0xad, 0x75, 0x2f, 0x3d, 0x42, 0x10, 0x8c, 0x01, 0x21,
	0x20, 0xec, 0x95, 0x13, 0x2a, 0x28, 0xfd, 0xd0, 0x72, 0x70, 0xe4, 0x83, 0x08, 0xd1, 0x3e, 0x40,
	0x8e, 0x8c, 0xa1, 0x98, 0x66, 0x63, 0x76, 0x83, 0x2f, 0xe5, 0x03, 0xf9, 0x38, 0x92, 0xec, 0xa6,
	0x66, 0x7b, 0x2b, 0xb1, 0x1f, 0x67, 0x6e, 0x7e, 0x7b, 0xff, 0xf9, 0xff, 0x27, 0x70, 0xbc, 0xe7,
	0x4d, 0xc3, 0x7f, 0x0a, 0x56, 0x37, 0x5c, 0xf2, 0xe0, 0x55, 0xc1, 0x79, 0x51, 0xe2, 0xba, 0xaf,
	0xf6, 0xed, 0xb7, 0xb5, 0xbc, 0xbd, 0x43, 0x21, 0xb3, 0xbb, 0x5a, 0x0d, 0x44, 0xbf, 0x09, 0xcc,
	0xaf, 0x7b, 0x84, 0x9e, 0x80, 0x93, 0xe4, 0x3e, 0x09, 0x49, 0x3c, 0x4b, 0x9d, 0x24, 0xa7, 0xab,
	0xee, 0x17, 0xfe, 0x3d, 0xc9, 0x7d, 0xa7, 0xef, 0xe9, 0xaa, 0xeb, 0xdf, 0x08, 0x6c, 0x92, 0xdc,
	0x9f, 0xa9, 0xbe, 0xaa, 0xe8, 0x07, 0x00, 0xf5, 0xd2, 0x36, 0x93, 0xe8, 0x3f, 0x09, 0x49, 0x7c,
	0xb4, 0x09, 0x98, 0x12, 0xc0, 0x06, 0x01, 0xec, 0xeb, 0x20, 0x20, 0x1d, 0x4d, 0x77, 0x6c, 0x8a,
	0xb2, 0x6d, 0xaa, 0x9e, 0x7d, 0x3a, 0xcd, 0xfe, 0x9d, 0xee, 0xf4, 0x7c, 0x91, 0x99, 0x6c, 0x85,
	0x3f, 0x0f, 0x49, 0xbc, 0x48, 0x75, 0x15, 0xbd, 0x85, 0xe7, 0x9f, 0x50, 0x88, 0xac, 0xc0, 0x14,
	0x45, 0xcd, 0x2b, 0x81, 0xd4, 0x07, 0x57, 0xb7, 0xfa, 0x3d, 0x17, 0xe9, 0x50, 0x46, 0xd7, 0x70,
	0x7a, 0x95, 0xe7, 0x4a, 0x51, 0x8a, 0x3f, 0x5a, 0x14, 0x72, 0x64, 0x00, 0xf9, 0x87, 0x01, 0xce,
	0xd8, 0x80, 0xe8, 0x12, 0x96, 0x37, 0x75, 0x9e, 0x49, 0x34, 0x9f, 0xb1, 0xf8, 0xaa, 0xf5, 0x3a,
	0x86, 0xde, 0x73, 0xf0, 0x4c, 0x7c, 0x52, 0xf4, 0x1b, 0x58, 0x6e, 0xb1, 0xc4, 0x89, 0x3f, 0x8c,
	0xd6, 0x70, 0xb6, 0x43, 0xd9, 0x89, 0x57, 0x73, 0x62, 0x62, 0x41, 0x0d, 0x74, 0x5b, 0x1d, 0x02,
	0x7a, 0x73, 0x62, 0x6c, 0x7e, 0x01, 0x2f, 0x35, 0xf0, 0xb9, 0xda, 0xf1, 0xdb, 0xaa, 0xf8, 0x4f,
	0x6e, 0x05, 0xde, 0x0e, 0xe5, 0x55, 0x59, 0x9a, 0xf3, 0xd1, 0x7b, 0xa0, 0xbd, 0x62, 0xdd, 0xd4,
	0x46, 0xbc, 0x06, 0x57, 0x5f, 0xb7, 0x4f, 0xc2, 0x59, 0x7c, 0xb4, 0x71, 0x99, 0x5e, 0x7c, 0xe8,
	0x6f, 0x7e, 0xcd, 0xc0, 0xd5, 0x18, 0x3d, 0x87, 0xc5, 0x7d, 0xa4, 0xf4, 0x05, 0x7b, 0x18, 0x6f,
	0x70, 0xca, 0x1e, 0x9e, 0xc7, 0x05, 0x3c, 0x1b, 0x27, 0x40, 0x3d, 0x66, 0xc9, 0xd3, 0xce, 0x8d,
	0x73, 0xa0, 0x1e, 0xb3, 0xc4, 0x62, 0xe1, 0x2e, 0xe1, 0xc4, 0x0c, 0x86, 0xae, 0x98, 0x35, 0xa9,
	0x60, 0xc9, 0x2c, 0x7e, 0x28, 0x7c, 0x14, 0x93, 0xc2, 0x0f, 0x73, 0xb3, 0xe3, 0x1f, 0xe1, 0xd8,
	0x30, 0x9f, 0x9e, 0x31, 0x5b, 0x18, 0x76, 0x78, 0x7b, 0x7f, 0x22, 0x66, 0xe2, 0x8f, 0x92, 0xb0,
	0x9f, 0xf7, 0x9f, 0xf6, 0xbb, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x2b, 0xe1, 0x62, 0x35, 0xb6,
	0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BorrowsClient is the client API for Borrows service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BorrowsClient interface {
	// ADD
	AddBorrow(ctx context.Context, in *AddBorrowRequest, opts ...grpc.CallOption) (*MessageResponse, error)
	// UPDATE
	UpdateBorrow(ctx context.Context, in *UpdateBorrowRequest, opts ...grpc.CallOption) (*MessageResponse, error)
	// DELETE
	DeleteBorrow(ctx context.Context, in *DeleteBorrowRequest, opts ...grpc.CallOption) (*MessageResponse, error)
	// GET
	GetBookBorrows(ctx context.Context, in *GetBookBorrowsRequest, opts ...grpc.CallOption) (*GetBorrowsResponse, error)
	GetUserBorrows(ctx context.Context, in *GetUserBorrowsRequest, opts ...grpc.CallOption) (*GetBorrowsResponse, error)
	GetAllBorrows(ctx context.Context, in *GetAllBorrowsRequest, opts ...grpc.CallOption) (*GetBorrowsResponse, error)
	GetUserOnGoingBorrows(ctx context.Context, in *GetUserBorrowsRequest, opts ...grpc.CallOption) (*GetBorrowsResponse, error)
}

type borrowsClient struct {
	cc grpc.ClientConnInterface
}

func NewBorrowsClient(cc grpc.ClientConnInterface) BorrowsClient {
	return &borrowsClient{cc}
}

func (c *borrowsClient) AddBorrow(ctx context.Context, in *AddBorrowRequest, opts ...grpc.CallOption) (*MessageResponse, error) {
	out := new(MessageResponse)
	err := c.cc.Invoke(ctx, "/Borrows/AddBorrow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *borrowsClient) UpdateBorrow(ctx context.Context, in *UpdateBorrowRequest, opts ...grpc.CallOption) (*MessageResponse, error) {
	out := new(MessageResponse)
	err := c.cc.Invoke(ctx, "/Borrows/UpdateBorrow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *borrowsClient) DeleteBorrow(ctx context.Context, in *DeleteBorrowRequest, opts ...grpc.CallOption) (*MessageResponse, error) {
	out := new(MessageResponse)
	err := c.cc.Invoke(ctx, "/Borrows/DeleteBorrow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *borrowsClient) GetBookBorrows(ctx context.Context, in *GetBookBorrowsRequest, opts ...grpc.CallOption) (*GetBorrowsResponse, error) {
	out := new(GetBorrowsResponse)
	err := c.cc.Invoke(ctx, "/Borrows/GetBookBorrows", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *borrowsClient) GetUserBorrows(ctx context.Context, in *GetUserBorrowsRequest, opts ...grpc.CallOption) (*GetBorrowsResponse, error) {
	out := new(GetBorrowsResponse)
	err := c.cc.Invoke(ctx, "/Borrows/GetUserBorrows", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *borrowsClient) GetAllBorrows(ctx context.Context, in *GetAllBorrowsRequest, opts ...grpc.CallOption) (*GetBorrowsResponse, error) {
	out := new(GetBorrowsResponse)
	err := c.cc.Invoke(ctx, "/Borrows/GetAllBorrows", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *borrowsClient) GetUserOnGoingBorrows(ctx context.Context, in *GetUserBorrowsRequest, opts ...grpc.CallOption) (*GetBorrowsResponse, error) {
	out := new(GetBorrowsResponse)
	err := c.cc.Invoke(ctx, "/Borrows/GetUserOnGoingBorrows", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BorrowsServer is the server API for Borrows service.
type BorrowsServer interface {
	// ADD
	AddBorrow(context.Context, *AddBorrowRequest) (*MessageResponse, error)
	// UPDATE
	UpdateBorrow(context.Context, *UpdateBorrowRequest) (*MessageResponse, error)
	// DELETE
	DeleteBorrow(context.Context, *DeleteBorrowRequest) (*MessageResponse, error)
	// GET
	GetBookBorrows(context.Context, *GetBookBorrowsRequest) (*GetBorrowsResponse, error)
	GetUserBorrows(context.Context, *GetUserBorrowsRequest) (*GetBorrowsResponse, error)
	GetAllBorrows(context.Context, *GetAllBorrowsRequest) (*GetBorrowsResponse, error)
	GetUserOnGoingBorrows(context.Context, *GetUserBorrowsRequest) (*GetBorrowsResponse, error)
}

// UnimplementedBorrowsServer can be embedded to have forward compatible implementations.
type UnimplementedBorrowsServer struct {
}

func (*UnimplementedBorrowsServer) AddBorrow(ctx context.Context, req *AddBorrowRequest) (*MessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddBorrow not implemented")
}
func (*UnimplementedBorrowsServer) UpdateBorrow(ctx context.Context, req *UpdateBorrowRequest) (*MessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBorrow not implemented")
}
func (*UnimplementedBorrowsServer) DeleteBorrow(ctx context.Context, req *DeleteBorrowRequest) (*MessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBorrow not implemented")
}
func (*UnimplementedBorrowsServer) GetBookBorrows(ctx context.Context, req *GetBookBorrowsRequest) (*GetBorrowsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBookBorrows not implemented")
}
func (*UnimplementedBorrowsServer) GetUserBorrows(ctx context.Context, req *GetUserBorrowsRequest) (*GetBorrowsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserBorrows not implemented")
}
func (*UnimplementedBorrowsServer) GetAllBorrows(ctx context.Context, req *GetAllBorrowsRequest) (*GetBorrowsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllBorrows not implemented")
}
func (*UnimplementedBorrowsServer) GetUserOnGoingBorrows(ctx context.Context, req *GetUserBorrowsRequest) (*GetBorrowsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserOnGoingBorrows not implemented")
}

func RegisterBorrowsServer(s *grpc.Server, srv BorrowsServer) {
	s.RegisterService(&_Borrows_serviceDesc, srv)
}

func _Borrows_AddBorrow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBorrowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BorrowsServer).AddBorrow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Borrows/AddBorrow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BorrowsServer).AddBorrow(ctx, req.(*AddBorrowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Borrows_UpdateBorrow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBorrowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BorrowsServer).UpdateBorrow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Borrows/UpdateBorrow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BorrowsServer).UpdateBorrow(ctx, req.(*UpdateBorrowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Borrows_DeleteBorrow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBorrowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BorrowsServer).DeleteBorrow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Borrows/DeleteBorrow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BorrowsServer).DeleteBorrow(ctx, req.(*DeleteBorrowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Borrows_GetBookBorrows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBookBorrowsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BorrowsServer).GetBookBorrows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Borrows/GetBookBorrows",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BorrowsServer).GetBookBorrows(ctx, req.(*GetBookBorrowsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Borrows_GetUserBorrows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserBorrowsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BorrowsServer).GetUserBorrows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Borrows/GetUserBorrows",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BorrowsServer).GetUserBorrows(ctx, req.(*GetUserBorrowsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Borrows_GetAllBorrows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllBorrowsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BorrowsServer).GetAllBorrows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Borrows/GetAllBorrows",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BorrowsServer).GetAllBorrows(ctx, req.(*GetAllBorrowsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Borrows_GetUserOnGoingBorrows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserBorrowsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BorrowsServer).GetUserOnGoingBorrows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Borrows/GetUserOnGoingBorrows",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BorrowsServer).GetUserOnGoingBorrows(ctx, req.(*GetUserBorrowsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Borrows_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Borrows",
	HandlerType: (*BorrowsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddBorrow",
			Handler:    _Borrows_AddBorrow_Handler,
		},
		{
			MethodName: "UpdateBorrow",
			Handler:    _Borrows_UpdateBorrow_Handler,
		},
		{
			MethodName: "DeleteBorrow",
			Handler:    _Borrows_DeleteBorrow_Handler,
		},
		{
			MethodName: "GetBookBorrows",
			Handler:    _Borrows_GetBookBorrows_Handler,
		},
		{
			MethodName: "GetUserBorrows",
			Handler:    _Borrows_GetUserBorrows_Handler,
		},
		{
			MethodName: "GetAllBorrows",
			Handler:    _Borrows_GetAllBorrows_Handler,
		},
		{
			MethodName: "GetUserOnGoingBorrows",
			Handler:    _Borrows_GetUserOnGoingBorrows_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "borrows.proto",
}
