// Code generated by protoc-gen-go. DO NOT EDIT.
// source: books.proto

package books

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Book struct {
	BookId               int64    `protobuf:"varint,1,opt,name=BookId,proto3" json:"BookId,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	Author               string   `protobuf:"bytes,3,opt,name=Author,proto3" json:"Author,omitempty"`
	Category             string   `protobuf:"bytes,4,opt,name=Category,proto3" json:"Category,omitempty"`
	CoverURL             string   `protobuf:"bytes,5,opt,name=CoverURL,proto3" json:"CoverURL,omitempty"`
	Language             string   `protobuf:"bytes,6,opt,name=Language,proto3" json:"Language,omitempty"`
	Summary              string   `protobuf:"bytes,7,opt,name=Summary,proto3" json:"Summary,omitempty"`
	Borrows              int32    `protobuf:"varint,8,opt,name=Borrows,proto3" json:"Borrows,omitempty"`
	Likes                int32    `protobuf:"varint,9,opt,name=Likes,proto3" json:"Likes,omitempty"`
	Available            bool     `protobuf:"varint,10,opt,name=Available,proto3" json:"Available,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Book) Reset()         { *m = Book{} }
func (m *Book) String() string { return proto.CompactTextString(m) }
func (*Book) ProtoMessage()    {}
func (*Book) Descriptor() ([]byte, []int) {
	return fileDescriptor_01e0dc127ded4184, []int{0}
}

func (m *Book) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Book.Unmarshal(m, b)
}
func (m *Book) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Book.Marshal(b, m, deterministic)
}
func (m *Book) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Book.Merge(m, src)
}
func (m *Book) XXX_Size() int {
	return xxx_messageInfo_Book.Size(m)
}
func (m *Book) XXX_DiscardUnknown() {
	xxx_messageInfo_Book.DiscardUnknown(m)
}

var xxx_messageInfo_Book proto.InternalMessageInfo

func (m *Book) GetBookId() int64 {
	if m != nil {
		return m.BookId
	}
	return 0
}

func (m *Book) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Book) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *Book) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *Book) GetCoverURL() string {
	if m != nil {
		return m.CoverURL
	}
	return ""
}

func (m *Book) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *Book) GetSummary() string {
	if m != nil {
		return m.Summary
	}
	return ""
}

func (m *Book) GetBorrows() int32 {
	if m != nil {
		return m.Borrows
	}
	return 0
}

func (m *Book) GetLikes() int32 {
	if m != nil {
		return m.Likes
	}
	return 0
}

func (m *Book) GetAvailable() bool {
	if m != nil {
		return m.Available
	}
	return false
}

type AddBookRequest struct {
	Title                string   `protobuf:"bytes,1,opt,name=Title,proto3" json:"Title,omitempty"`
	Author               string   `protobuf:"bytes,2,opt,name=Author,proto3" json:"Author,omitempty"`
	Category             string   `protobuf:"bytes,3,opt,name=Category,proto3" json:"Category,omitempty"`
	CoverURL             string   `protobuf:"bytes,4,opt,name=CoverURL,proto3" json:"CoverURL,omitempty"`
	Language             string   `protobuf:"bytes,5,opt,name=Language,proto3" json:"Language,omitempty"`
	Summary              string   `protobuf:"bytes,6,opt,name=Summary,proto3" json:"Summary,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddBookRequest) Reset()         { *m = AddBookRequest{} }
func (m *AddBookRequest) String() string { return proto.CompactTextString(m) }
func (*AddBookRequest) ProtoMessage()    {}
func (*AddBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_01e0dc127ded4184, []int{1}
}

func (m *AddBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddBookRequest.Unmarshal(m, b)
}
func (m *AddBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddBookRequest.Marshal(b, m, deterministic)
}
func (m *AddBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddBookRequest.Merge(m, src)
}
func (m *AddBookRequest) XXX_Size() int {
	return xxx_messageInfo_AddBookRequest.Size(m)
}
func (m *AddBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddBookRequest proto.InternalMessageInfo

func (m *AddBookRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *AddBookRequest) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *AddBookRequest) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *AddBookRequest) GetCoverURL() string {
	if m != nil {
		return m.CoverURL
	}
	return ""
}

func (m *AddBookRequest) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *AddBookRequest) GetSummary() string {
	if m != nil {
		return m.Summary
	}
	return ""
}

type AddBookResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddBookResponse) Reset()         { *m = AddBookResponse{} }
func (m *AddBookResponse) String() string { return proto.CompactTextString(m) }
func (*AddBookResponse) ProtoMessage()    {}
func (*AddBookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_01e0dc127ded4184, []int{2}
}

func (m *AddBookResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddBookResponse.Unmarshal(m, b)
}
func (m *AddBookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddBookResponse.Marshal(b, m, deterministic)
}
func (m *AddBookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddBookResponse.Merge(m, src)
}
func (m *AddBookResponse) XXX_Size() int {
	return xxx_messageInfo_AddBookResponse.Size(m)
}
func (m *AddBookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddBookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddBookResponse proto.InternalMessageInfo

func (m *AddBookResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GetBookRequest struct {
	BookId               int64    `protobuf:"varint,1,opt,name=BookId,proto3" json:"BookId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBookRequest) Reset()         { *m = GetBookRequest{} }
func (m *GetBookRequest) String() string { return proto.CompactTextString(m) }
func (*GetBookRequest) ProtoMessage()    {}
func (*GetBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_01e0dc127ded4184, []int{3}
}

func (m *GetBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBookRequest.Unmarshal(m, b)
}
func (m *GetBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBookRequest.Marshal(b, m, deterministic)
}
func (m *GetBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBookRequest.Merge(m, src)
}
func (m *GetBookRequest) XXX_Size() int {
	return xxx_messageInfo_GetBookRequest.Size(m)
}
func (m *GetBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBookRequest proto.InternalMessageInfo

func (m *GetBookRequest) GetBookId() int64 {
	if m != nil {
		return m.BookId
	}
	return 0
}

type GetBookResponse struct {
	BookId               int64    `protobuf:"varint,1,opt,name=BookId,proto3" json:"BookId,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	Author               string   `protobuf:"bytes,3,opt,name=Author,proto3" json:"Author,omitempty"`
	Category             string   `protobuf:"bytes,4,opt,name=Category,proto3" json:"Category,omitempty"`
	CoverURL             string   `protobuf:"bytes,5,opt,name=CoverURL,proto3" json:"CoverURL,omitempty"`
	Language             string   `protobuf:"bytes,6,opt,name=Language,proto3" json:"Language,omitempty"`
	Summary              string   `protobuf:"bytes,7,opt,name=Summary,proto3" json:"Summary,omitempty"`
	Borrows              int32    `protobuf:"varint,8,opt,name=Borrows,proto3" json:"Borrows,omitempty"`
	Likes                int32    `protobuf:"varint,9,opt,name=Likes,proto3" json:"Likes,omitempty"`
	Available            bool     `protobuf:"varint,10,opt,name=Available,proto3" json:"Available,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBookResponse) Reset()         { *m = GetBookResponse{} }
func (m *GetBookResponse) String() string { return proto.CompactTextString(m) }
func (*GetBookResponse) ProtoMessage()    {}
func (*GetBookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_01e0dc127ded4184, []int{4}
}

func (m *GetBookResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBookResponse.Unmarshal(m, b)
}
func (m *GetBookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBookResponse.Marshal(b, m, deterministic)
}
func (m *GetBookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBookResponse.Merge(m, src)
}
func (m *GetBookResponse) XXX_Size() int {
	return xxx_messageInfo_GetBookResponse.Size(m)
}
func (m *GetBookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBookResponse proto.InternalMessageInfo

func (m *GetBookResponse) GetBookId() int64 {
	if m != nil {
		return m.BookId
	}
	return 0
}

func (m *GetBookResponse) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *GetBookResponse) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *GetBookResponse) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *GetBookResponse) GetCoverURL() string {
	if m != nil {
		return m.CoverURL
	}
	return ""
}

func (m *GetBookResponse) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *GetBookResponse) GetSummary() string {
	if m != nil {
		return m.Summary
	}
	return ""
}

func (m *GetBookResponse) GetBorrows() int32 {
	if m != nil {
		return m.Borrows
	}
	return 0
}

func (m *GetBookResponse) GetLikes() int32 {
	if m != nil {
		return m.Likes
	}
	return 0
}

func (m *GetBookResponse) GetAvailable() bool {
	if m != nil {
		return m.Available
	}
	return false
}

type GetBooksRequest struct {
	Category             string   `protobuf:"bytes,1,opt,name=Category,proto3" json:"Category,omitempty"`
	Language             string   `protobuf:"bytes,2,opt,name=Language,proto3" json:"Language,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBooksRequest) Reset()         { *m = GetBooksRequest{} }
func (m *GetBooksRequest) String() string { return proto.CompactTextString(m) }
func (*GetBooksRequest) ProtoMessage()    {}
func (*GetBooksRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_01e0dc127ded4184, []int{5}
}

func (m *GetBooksRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBooksRequest.Unmarshal(m, b)
}
func (m *GetBooksRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBooksRequest.Marshal(b, m, deterministic)
}
func (m *GetBooksRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBooksRequest.Merge(m, src)
}
func (m *GetBooksRequest) XXX_Size() int {
	return xxx_messageInfo_GetBooksRequest.Size(m)
}
func (m *GetBooksRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBooksRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBooksRequest proto.InternalMessageInfo

func (m *GetBooksRequest) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *GetBooksRequest) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

type GetBooksResponse struct {
	Books                []*Book  `protobuf:"bytes,1,rep,name=Books,proto3" json:"Books,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBooksResponse) Reset()         { *m = GetBooksResponse{} }
func (m *GetBooksResponse) String() string { return proto.CompactTextString(m) }
func (*GetBooksResponse) ProtoMessage()    {}
func (*GetBooksResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_01e0dc127ded4184, []int{6}
}

func (m *GetBooksResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBooksResponse.Unmarshal(m, b)
}
func (m *GetBooksResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBooksResponse.Marshal(b, m, deterministic)
}
func (m *GetBooksResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBooksResponse.Merge(m, src)
}
func (m *GetBooksResponse) XXX_Size() int {
	return xxx_messageInfo_GetBooksResponse.Size(m)
}
func (m *GetBooksResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBooksResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBooksResponse proto.InternalMessageInfo

func (m *GetBooksResponse) GetBooks() []*Book {
	if m != nil {
		return m.Books
	}
	return nil
}

type DeleteBookRequest struct {
	BookId               int64    `protobuf:"varint,1,opt,name=BookId,proto3" json:"BookId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteBookRequest) Reset()         { *m = DeleteBookRequest{} }
func (m *DeleteBookRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteBookRequest) ProtoMessage()    {}
func (*DeleteBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_01e0dc127ded4184, []int{7}
}

func (m *DeleteBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteBookRequest.Unmarshal(m, b)
}
func (m *DeleteBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteBookRequest.Marshal(b, m, deterministic)
}
func (m *DeleteBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteBookRequest.Merge(m, src)
}
func (m *DeleteBookRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteBookRequest.Size(m)
}
func (m *DeleteBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteBookRequest proto.InternalMessageInfo

func (m *DeleteBookRequest) GetBookId() int64 {
	if m != nil {
		return m.BookId
	}
	return 0
}

type DeleteBookResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteBookResponse) Reset()         { *m = DeleteBookResponse{} }
func (m *DeleteBookResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteBookResponse) ProtoMessage()    {}
func (*DeleteBookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_01e0dc127ded4184, []int{8}
}

func (m *DeleteBookResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteBookResponse.Unmarshal(m, b)
}
func (m *DeleteBookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteBookResponse.Marshal(b, m, deterministic)
}
func (m *DeleteBookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteBookResponse.Merge(m, src)
}
func (m *DeleteBookResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteBookResponse.Size(m)
}
func (m *DeleteBookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteBookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteBookResponse proto.InternalMessageInfo

func (m *DeleteBookResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type UpdateBookRequest struct {
	BookId               int64    `protobuf:"varint,1,opt,name=BookId,proto3" json:"BookId,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	Author               string   `protobuf:"bytes,3,opt,name=Author,proto3" json:"Author,omitempty"`
	Category             string   `protobuf:"bytes,4,opt,name=Category,proto3" json:"Category,omitempty"`
	CoverURL             string   `protobuf:"bytes,5,opt,name=CoverURL,proto3" json:"CoverURL,omitempty"`
	Language             string   `protobuf:"bytes,6,opt,name=Language,proto3" json:"Language,omitempty"`
	Summary              string   `protobuf:"bytes,7,opt,name=Summary,proto3" json:"Summary,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateBookRequest) Reset()         { *m = UpdateBookRequest{} }
func (m *UpdateBookRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateBookRequest) ProtoMessage()    {}
func (*UpdateBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_01e0dc127ded4184, []int{9}
}

func (m *UpdateBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateBookRequest.Unmarshal(m, b)
}
func (m *UpdateBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateBookRequest.Marshal(b, m, deterministic)
}
func (m *UpdateBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateBookRequest.Merge(m, src)
}
func (m *UpdateBookRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateBookRequest.Size(m)
}
func (m *UpdateBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateBookRequest proto.InternalMessageInfo

func (m *UpdateBookRequest) GetBookId() int64 {
	if m != nil {
		return m.BookId
	}
	return 0
}

func (m *UpdateBookRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *UpdateBookRequest) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *UpdateBookRequest) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *UpdateBookRequest) GetCoverURL() string {
	if m != nil {
		return m.CoverURL
	}
	return ""
}

func (m *UpdateBookRequest) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *UpdateBookRequest) GetSummary() string {
	if m != nil {
		return m.Summary
	}
	return ""
}

type UpdateBookResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateBookResponse) Reset()         { *m = UpdateBookResponse{} }
func (m *UpdateBookResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateBookResponse) ProtoMessage()    {}
func (*UpdateBookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_01e0dc127ded4184, []int{10}
}

func (m *UpdateBookResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateBookResponse.Unmarshal(m, b)
}
func (m *UpdateBookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateBookResponse.Marshal(b, m, deterministic)
}
func (m *UpdateBookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateBookResponse.Merge(m, src)
}
func (m *UpdateBookResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateBookResponse.Size(m)
}
func (m *UpdateBookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateBookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateBookResponse proto.InternalMessageInfo

func (m *UpdateBookResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Book)(nil), "Book")
	proto.RegisterType((*AddBookRequest)(nil), "AddBookRequest")
	proto.RegisterType((*AddBookResponse)(nil), "AddBookResponse")
	proto.RegisterType((*GetBookRequest)(nil), "GetBookRequest")
	proto.RegisterType((*GetBookResponse)(nil), "GetBookResponse")
	proto.RegisterType((*GetBooksRequest)(nil), "GetBooksRequest")
	proto.RegisterType((*GetBooksResponse)(nil), "GetBooksResponse")
	proto.RegisterType((*DeleteBookRequest)(nil), "DeleteBookRequest")
	proto.RegisterType((*DeleteBookResponse)(nil), "DeleteBookResponse")
	proto.RegisterType((*UpdateBookRequest)(nil), "UpdateBookRequest")
	proto.RegisterType((*UpdateBookResponse)(nil), "UpdateBookResponse")
}

func init() {
	proto.RegisterFile("books.proto", fileDescriptor_01e0dc127ded4184)
}

var fileDescriptor_01e0dc127ded4184 = []byte{
	// 457 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x95, 0xcb, 0x6a, 0xdb, 0x40,
	0x14, 0x86, 0x19, 0xc9, 0xba, 0xf8, 0x04, 0x22, 0x7b, 0x52, 0xca, 0xa0, 0x76, 0x21, 0xb4, 0x12,
	0x24, 0x4c, 0x20, 0x25, 0x0f, 0xe0, 0xb4, 0x50, 0x02, 0xee, 0x46, 0x6d, 0x1e, 0x40, 0x46, 0x83,
	0x6b, 0xac, 0x64, 0x5c, 0x8d, 0x94, 0x92, 0x7d, 0x17, 0xdd, 0xf7, 0x35, 0xfa, 0x1e, 0x7d, 0xad,
	0x32, 0xa3, 0xd1, 0xcd, 0xf2, 0x6d, 0xd9, 0x45, 0x57, 0xe6, 0x3f, 0xff, 0x30, 0x9c, 0xef, 0xfc,
	0x67, 0x2c, 0x38, 0x5b, 0x70, 0xbe, 0x16, 0x74, 0x93, 0xf3, 0x82, 0x87, 0x3f, 0x0d, 0x18, 0xdd,
	0x71, 0xbe, 0xc6, 0xaf, 0xc1, 0x96, 0xbf, 0xf7, 0x29, 0x41, 0x01, 0x8a, 0xcc, 0x58, 0x2b, 0xfc,
	0x0a, 0xac, 0x2f, 0xab, 0x22, 0x63, 0xc4, 0x08, 0x50, 0x34, 0x8e, 0x2b, 0x21, 0x4f, 0xcf, 0xca,
	0xe2, 0x2b, 0xcf, 0x89, 0xa9, 0xca, 0x5a, 0x61, 0x1f, 0xdc, 0xf7, 0x49, 0xc1, 0x96, 0x3c, 0x7f,
	0x21, 0x23, 0xe5, 0x34, 0x5a, 0x79, 0xfc, 0x99, 0xe5, 0x0f, 0xf1, 0x9c, 0x58, 0xda, 0xd3, 0x5a,
	0x7a, 0xf3, 0xe4, 0x69, 0x59, 0x26, 0x4b, 0x46, 0xec, 0xca, 0xab, 0x35, 0x26, 0xe0, 0x7c, 0x2e,
	0x1f, 0x1f, 0x93, 0xfc, 0x85, 0x38, 0xca, 0xaa, 0xa5, 0x74, 0xee, 0x78, 0x9e, 0xf3, 0xef, 0x82,
	0xb8, 0x01, 0x8a, 0xac, 0xb8, 0x96, 0xb2, 0xeb, 0xf9, 0x6a, 0xcd, 0x04, 0x19, 0xab, 0x7a, 0x25,
	0xf0, 0x5b, 0x18, 0xcf, 0x9e, 0x93, 0x55, 0x96, 0x2c, 0x32, 0x46, 0x20, 0x40, 0x91, 0x1b, 0xb7,
	0x85, 0xf0, 0x37, 0x82, 0xf3, 0x59, 0x9a, 0x4a, 0xee, 0x98, 0x7d, 0x2b, 0x99, 0x28, 0x5a, 0x78,
	0xb4, 0x1b, 0xde, 0xd8, 0x0b, 0x6f, 0x1e, 0x80, 0x1f, 0x1d, 0x80, 0xb7, 0xf6, 0xc3, 0xdb, 0x3d,
	0xf8, 0xf0, 0x12, 0xbc, 0xa6, 0x5b, 0xb1, 0xe1, 0x4f, 0x42, 0x1d, 0xfe, 0xc4, 0x84, 0x90, 0xf7,
	0x54, 0x0d, 0xd7, 0x32, 0x8c, 0xe0, 0xfc, 0x23, 0x2b, 0xba, 0x68, 0x7b, 0xf2, 0x0e, 0x7f, 0x19,
	0xe0, 0x35, 0x47, 0xf5, 0xbd, 0xff, 0x77, 0xe3, 0xbe, 0x19, 0x8a, 0xa8, 0x07, 0xd8, 0xc5, 0x41,
	0x43, 0x9c, 0xa6, 0x65, 0xa3, 0xdf, 0x72, 0x78, 0x0d, 0x93, 0xf6, 0x2a, 0x3d, 0xe0, 0x37, 0x60,
	0xa9, 0x02, 0x41, 0x81, 0x19, 0x9d, 0xdd, 0x58, 0x54, 0x8d, 0xbf, 0xaa, 0x85, 0x97, 0x30, 0xfd,
	0xc0, 0x32, 0x56, 0xb0, 0x53, 0xe2, 0xa3, 0x80, 0xbb, 0x87, 0x8f, 0x2e, 0xc6, 0x1f, 0x04, 0xd3,
	0x87, 0x4d, 0x9a, 0x9c, 0x74, 0xfb, 0xbf, 0x1c, 0xb8, 0x24, 0xef, 0x82, 0x1c, 0x23, 0xbf, 0xf9,
	0x61, 0x34, 0x1b, 0x82, 0xaf, 0xc0, 0xd1, 0x6f, 0x09, 0x7b, 0xb4, 0xff, 0x1f, 0xe0, 0x4f, 0xe8,
	0xf6, 0x33, 0xbb, 0x02, 0x47, 0x27, 0x88, 0x3d, 0xda, 0x7f, 0x56, 0xfe, 0x84, 0x6e, 0x3f, 0x9e,
	0x6b, 0x70, 0xeb, 0xbc, 0x71, 0xe3, 0xd6, 0x5b, 0xe4, 0x4f, 0xe9, 0x60, 0x19, 0x6e, 0x01, 0xda,
	0x08, 0x31, 0xa6, 0x83, 0xf0, 0xfd, 0x0b, 0xba, 0x23, 0xe3, 0x5b, 0x80, 0x96, 0x1f, 0x63, 0x3a,
	0x48, 0xd5, 0xbf, 0xa0, 0xc3, 0x01, 0x2d, 0x6c, 0xf5, 0x1d, 0x78, 0xf7, 0x37, 0x00, 0x00, 0xff,
	0xff, 0x3f, 0xaf, 0x99, 0x71, 0x16, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BorrowsClient is the client API for Borrows service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BorrowsClient interface {
	AddBook(ctx context.Context, in *AddBookRequest, opts ...grpc.CallOption) (*AddBookResponse, error)
	GetBook(ctx context.Context, in *GetBookRequest, opts ...grpc.CallOption) (*GetBookResponse, error)
	GetBooks(ctx context.Context, in *GetBooksRequest, opts ...grpc.CallOption) (*GetBooksResponse, error)
	DeleteBook(ctx context.Context, in *DeleteBookRequest, opts ...grpc.CallOption) (*DeleteBookResponse, error)
	UpdateBook(ctx context.Context, in *UpdateBookRequest, opts ...grpc.CallOption) (*UpdateBookResponse, error)
}

type borrowsClient struct {
	cc grpc.ClientConnInterface
}

func NewBorrowsClient(cc grpc.ClientConnInterface) BorrowsClient {
	return &borrowsClient{cc}
}

func (c *borrowsClient) AddBook(ctx context.Context, in *AddBookRequest, opts ...grpc.CallOption) (*AddBookResponse, error) {
	out := new(AddBookResponse)
	err := c.cc.Invoke(ctx, "/Borrows/AddBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *borrowsClient) GetBook(ctx context.Context, in *GetBookRequest, opts ...grpc.CallOption) (*GetBookResponse, error) {
	out := new(GetBookResponse)
	err := c.cc.Invoke(ctx, "/Borrows/GetBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *borrowsClient) GetBooks(ctx context.Context, in *GetBooksRequest, opts ...grpc.CallOption) (*GetBooksResponse, error) {
	out := new(GetBooksResponse)
	err := c.cc.Invoke(ctx, "/Borrows/GetBooks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *borrowsClient) DeleteBook(ctx context.Context, in *DeleteBookRequest, opts ...grpc.CallOption) (*DeleteBookResponse, error) {
	out := new(DeleteBookResponse)
	err := c.cc.Invoke(ctx, "/Borrows/DeleteBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *borrowsClient) UpdateBook(ctx context.Context, in *UpdateBookRequest, opts ...grpc.CallOption) (*UpdateBookResponse, error) {
	out := new(UpdateBookResponse)
	err := c.cc.Invoke(ctx, "/Borrows/UpdateBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BorrowsServer is the server API for Borrows service.
type BorrowsServer interface {
	AddBook(context.Context, *AddBookRequest) (*AddBookResponse, error)
	GetBook(context.Context, *GetBookRequest) (*GetBookResponse, error)
	GetBooks(context.Context, *GetBooksRequest) (*GetBooksResponse, error)
	DeleteBook(context.Context, *DeleteBookRequest) (*DeleteBookResponse, error)
	UpdateBook(context.Context, *UpdateBookRequest) (*UpdateBookResponse, error)
}

// UnimplementedBorrowsServer can be embedded to have forward compatible implementations.
type UnimplementedBorrowsServer struct {
}

func (*UnimplementedBorrowsServer) AddBook(ctx context.Context, req *AddBookRequest) (*AddBookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddBook not implemented")
}
func (*UnimplementedBorrowsServer) GetBook(ctx context.Context, req *GetBookRequest) (*GetBookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBook not implemented")
}
func (*UnimplementedBorrowsServer) GetBooks(ctx context.Context, req *GetBooksRequest) (*GetBooksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBooks not implemented")
}
func (*UnimplementedBorrowsServer) DeleteBook(ctx context.Context, req *DeleteBookRequest) (*DeleteBookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBook not implemented")
}
func (*UnimplementedBorrowsServer) UpdateBook(ctx context.Context, req *UpdateBookRequest) (*UpdateBookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBook not implemented")
}

func RegisterBorrowsServer(s *grpc.Server, srv BorrowsServer) {
	s.RegisterService(&_Borrows_serviceDesc, srv)
}

func _Borrows_AddBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BorrowsServer).AddBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Borrows/AddBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BorrowsServer).AddBook(ctx, req.(*AddBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Borrows_GetBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BorrowsServer).GetBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Borrows/GetBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BorrowsServer).GetBook(ctx, req.(*GetBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Borrows_GetBooks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBooksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BorrowsServer).GetBooks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Borrows/GetBooks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BorrowsServer).GetBooks(ctx, req.(*GetBooksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Borrows_DeleteBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BorrowsServer).DeleteBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Borrows/DeleteBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BorrowsServer).DeleteBook(ctx, req.(*DeleteBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Borrows_UpdateBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BorrowsServer).UpdateBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Borrows/UpdateBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BorrowsServer).UpdateBook(ctx, req.(*UpdateBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Borrows_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Borrows",
	HandlerType: (*BorrowsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddBook",
			Handler:    _Borrows_AddBook_Handler,
		},
		{
			MethodName: "GetBook",
			Handler:    _Borrows_GetBook_Handler,
		},
		{
			MethodName: "GetBooks",
			Handler:    _Borrows_GetBooks_Handler,
		},
		{
			MethodName: "DeleteBook",
			Handler:    _Borrows_DeleteBook_Handler,
		},
		{
			MethodName: "UpdateBook",
			Handler:    _Borrows_UpdateBook_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "books.proto",
}
